language: python
python:
  - '2.7'

env:
  global:
    - BS_PIP_ALLOWED=1
    - BS_ECHO_DEBUG=1
    - SALT_ARGS="-l debug --local --retcode-passthrough --pillar-root=tests/example --file-root=$PWD"
  matrix:
    - STATE=couchdb2
    - STATE=couchdb2.source
    - STATE=couchdb2.configure
    - STATE=couchdb2.deps
    - STATE=couchdb2.install
    - STATE=couchdb2.user

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo -E sh -s -- stable

install:
  # See what kind of travis box you're on to help with making your states
  # compatible with travis
  - sudo salt-call grains.items --local

script:
  - sudo salt-call state.show_sls $STATE $SALT_ARGS
  - sudo salt-call state.sls $STATE $SALT_ARGS

  # Idempotence check
  - sudo salt-call state.sls $STATE $SALT_ARGS > /tmp/second
  - cat /tmp/second
  - bash -c '! grep -q "^Not Run:" /tmp/second'
